Import libraries

In [26]:
import requests, re
import pandas as pd

In [27]:
pd.set_option('display.max_columns', None)

### Function to get a Google spreadsheet and convert it into a dataframe
Param: the ID of the Google document, ID of the spreadsheet

In [28]:
def get_dataframe(document_id, sheet_id):
    url = f"https://docs.google.com/spreadsheets/d/{document_id}/export?format=csv&gid={sheet_id}"
    df = pd.read_csv(url, header=0)
    return df

In [29]:
df = get_dataframe(doc_id, sheet_id)
df.head()

NameError: name 'doc_id' is not defined

### Get data from spreadsheet

In [30]:
doc_id = "1V_YG2Ymlb6jB4qlLQbF_glHqj5HmKfNdUR09hAdyLHk"
sheet_id = "0"   # = gid

df = get_dataframe(doc_id, sheet_id)
df.head()

,Name,"Stand (Kurfürsten, Fürsten, etc.)",Reichkreis,Reichs-\nmatrikel\n1521,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,Anmerkung,Unnamed: 33
0,Böhmen,Kurfürsten,-,4,-,-,-,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN
1,Brandenburg,Kurfürsten,oS,7,23,7,16,4,+,x,x,x,-,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x,NaN,NaN
2,Köln,Kurfürsten,KR,3,24,9,15,0,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x,NaN,NaN
3,Mainz,Kurfürsten,KR,1,24,14,10,23,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±,NaN,NaN
4,Pfalz,Kurfürsten,KR,5,23,11,12,20,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o,NaN,NaN

In [31]:
df.head(10)

,Name,"Stand (Kurfürsten, Fürsten, etc.)",Reichkreis,Reichs-\nmatrikel\n1521,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,Anmerkung,Unnamed: 33
0,Böhmen,Kurfürsten,-,4,-,-,-,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN
1,Brandenburg,Kurfürsten,oS,7,23,7,16,4,+,x,x,x,-,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x,NaN,NaN
2,Köln,Kurfürsten,KR,3,24,9,15,0,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x,NaN,NaN
3,Mainz,Kurfürsten,KR,1,24,14,10,23,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±,NaN,NaN
4,Pfalz,Kurfürsten,KR,5,23,11,12,20,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o,NaN,NaN
5,Sachsen,Kurfürsten,OS,6,20,6,14,0+,x,x,+,-,(+),x,-,x,x,x,x,-,+,x,+,x,x,x,x,+,x,x,x,+,NaN,NaN
6,Trier,Kurfürsten,KR,2,24,11,13,1,+,±,x,+,x,+,x,x,x,x,x,x,+,x,+,+,x,x,+,+,x,+,x,+,NaN,NaN
7,Augsburg,Geistliche Fürsten,S,11,22,15,7,1,+,x,-,x,x,+,+,+,+,x,-,x,+,+,+,±,+,+,+,+,x,x,+,+,NaN,NaN
8,Bamberg,Geistliche Fürsten,F,5,24,8,16,5,±,+,o,x,o,±,+,+,+,x,±,x,x,x,x,x,x,+,x,x,x,x,x,x,NaN,NaN
9,Basel,Geistliche Fürsten,R,26,14,0,14,0,x,-,-,-,-,x,x,x,x,x,-,-,x,-,-,x,-,x,x,x,-,x,x,x,NaN,NaN

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Name                               407 non-null    str
 1   Stand (Kurfürsten, Fürsten, etc.)  410 non-null    str
 2   Reichkreis                         398 non-null    str
 3   Reichs-
matrikel
1521              381 non-null    str
 4   Besuchte
RTT                       405 non-null    str
 5   Persönl.
besuchte
RTT              405 non-null    str
 6   Vertretene
RTT                     406 non-null    str
 7   Abschieds-
unterzeichnung          405 non-null    str
 8   W1521                              294 non-null    str
 9   N1524                              292 non-null    str
 10  A1526                              292 non-null    str
 11  S1526                              292 non-null    str
 12  R1527                              291 non-null    str
 13  S1529                              291 non-null    str
 14  A1530                              291 non-null    str
 15  R1532                              283 non-null    str
 16  R1541                              283 non-null    str
 17  S1542                              280 non-null    str
 18  N1542                              278 non-null    str
 19  N1543                              277 non-null    str
 20  S1544                              273 non-null    str
 21  W1545                              275 non-null    str
 22  A1548                              273 non-null    str
 23  A1551                              271 non-null    str
 24  A1555                              267 non-null    str
 25  R1557                              267 non-null    str
 26  A1559                              264 non-null    str
 27  A1566                              263 non-null    str
 28  R1567                              265 non-null    str
 29  S1570                              265 non-null    str
 30  R1576                              267 non-null    str
 31  A1582                              269 non-null    str
 32  Anmerkung                          152 non-null    str
 33  Unnamed: 33                        1 non-null      str
dtypes: str(34)
memory usage: 109.0 KB

In [33]:
df.describe()

,Name,"Stand (Kurfürsten, Fürsten, etc.)",Reichkreis,Reichs-\nmatrikel\n1521,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,Anmerkung,Unnamed: 33
count,407,410,398,381,405,405,406,405,294,292,292,292,291,291,291,283,283,280,278,277,273,275,273,271,267,267,264,263,265,265,267,269,152,1
unique,379,9,17,149,26,25,26,14,9,7,7,9,10,11,13,12,10,9,10,8,10,9,9,11,7,10,10,10,8,11,10,13,108,1
top,Brandenburg,Grafen und Herren,S,4,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,x,x,-,x,+,-,x,x,x,(Eidgenossenschaft),
freq,3,135,114,8,104,192,129,366,192,226,249,195,220,188,158,160,139,124,165,143,102,120,100,118,104,112,87,78,137,113,127,107,14,1

In [34]:
df.shape

(410, 34)

In [35]:
df.shape[0]

410

In [36]:
df.shape[1]

34

In [37]:
df.columns

Index(['Name', 'Stand (Kurfürsten, Fürsten, etc.)', 'Reichkreis',
       'Reichs-\nmatrikel\n1521', 'Besuchte\nRTT', 'Persönl.\nbesuchte\nRTT',
       'Vertretene\nRTT', 'Abschieds-\nunterzeichnung', 'W1521', 'N1524',
       'A1526', 'S1526', 'R1527', 'S1529', 'A1530', 'R1532', 'R1541', 'S1542',
       'N1542', 'N1543', 'S1544', 'W1545', 'A1548', 'A1551', 'A1555', 'R1557',
       'A1559', 'A1566', 'R1567', 'S1570', 'R1576', 'A1582', 'Anmerkung',
       'Unnamed: 33'],
      dtype='str')

In [38]:
# Extract column labels from the DataFrame and store them as a list
cols = list(df.columns)
cols

['Name',
 'Stand (Kurfürsten, Fürsten, etc.)',
 'Reichkreis',
 'Reichs-\nmatrikel\n1521',
 'Besuchte\nRTT',
 'Persönl.\nbesuchte\nRTT',
 'Vertretene\nRTT',
 'Abschieds-\nunterzeichnung',
 'W1521',
 'N1524',
 'A1526',
 'S1526',
 'R1527',
 'S1529',
 'A1530',
 'R1532',
 'R1541',
 'S1542',
 'N1542',
 'N1543',
 'S1544',
 'W1545',
 'A1548',
 'A1551',
 'A1555',
 'R1557',
 'A1559',
 'A1566',
 'R1567',
 'S1570',
 'R1576',
 'A1582',
 'Anmerkung',
 'Unnamed: 33']

In [39]:
# Iterate over all column names and print each one
for col in cols:
    print(col)

Name
Stand (Kurfürsten, Fürsten, etc.)
Reichkreis
Reichs-
matrikel
1521
Besuchte
RTT
Persönl.
besuchte
RTT
Vertretene
RTT
Abschieds-
unterzeichnung
W1521
N1524
A1526
S1526
R1527
S1529
A1530
R1532
R1541
S1542
N1542
N1543
S1544
W1545
A1548
A1551
A1555
R1557
A1559
A1566
R1567
S1570
R1576
A1582
Anmerkung
Unnamed: 33

In [40]:
rt_cols = cols[8:32]

rt_cols

['W1521',
 'N1524',
 'A1526',
 'S1526',
 'R1527',
 'S1529',
 'A1530',
 'R1532',
 'R1541',
 'S1542',
 'N1542',
 'N1543',
 'S1544',
 'W1545',
 'A1548',
 'A1551',
 'A1555',
 'R1557',
 'A1559',
 'A1566',
 'R1567',
 'S1570',
 'R1576',
 'A1582']

In [41]:
df[cols[:2]]   # first two columns

                 Name Stand (Kurfürsten, Fürsten, etc.)
0              Böhmen                        Kurfürsten
1         Brandenburg                        Kurfürsten
2                Köln                        Kurfürsten
3               Mainz                        Kurfürsten
4               Pfalz                        Kurfürsten
..                ...                               ...
405           Wetzlar                      Reichsstädte
406           Wimpfen                      Reichsstädte
407         Windsheim                      Reichsstädte
408             Worms                      Reichsstädte
409  Zell/Hammersbach                      Reichsstädte

[410 rows x 2 columns]

In [42]:
# Get unique values for each column in rt_cols
df[rt_cols].apply(pd.Series.unique)

W1521            [-,  + , ±, x,  +, nan, F+,  F+, - ,  ++]
N1524                      [-, x, ±,  +, nan, F±, - ,  ++]
A1526                        [-, x, o,  +, nan, Fx, - , ±]
S1526              [-, x,  +, ±, nan, Fx, F+, - , xx, (±)]
R1527          [-, x, o, (+), nan, Fx, ±,  F+, - , xx,  +]
S1529    [-, x,  +, ±, nan, F+,  F+, - , (+), xx, ±+, (±)]
A1530    [-, o,  +, ±, x, nan, F+,  F+, Fx, - , (+), xx...
R1532    [-, o, x, ±,  +, nan, F+, Fx,  Fx, - ,  ++,  +...
R1541          [-, o, x, ±,  +, nan, F+,  Fx, xx, ±+,  +x]
S1542              [-, o, x, ±,  +, nan, F+,  Fx, xx,  +x]
N1542           [-, x, o, ±, nan,  +, F+, Fx, xx, ox,  +x]
N1543                   [-, x, o, nan,  +, Fx, xx, ox,  ±]
S1544          [-,  +, ±, x, nan, F+, Fx, xx,  ++,  +x,  ]
W1545               [-, x, o,  +, nan, ±, F+, Fx, xx,  +x]
A1548             [-,  +, ±, x, nan, F+, Fx,  +x, xx, (±)]
A1551     [-, x, ±, o,  +, nan, F+, Fx, xx,  +x,   +,  ++]
A1555                        [-, x, o,  +, nan, ±, Fx, xx]
R1557          [-, x, o,  +, nan, ±, F+, Fx, xx,  +x,  ++]
A1559         [-, x, ±,  +, nan, Fx, F±, F+,  +x, xx,  ++]
A1566        [-, x,  +, ±, nan, Fx, F+,  +x,  ++, xx, (o)]
R1567                   [-, x, o, nan,  +, Fx, ±, xx,  +x]
S1570     [-, x,  +, ±, nan, o, Fx, F+,  +x, xx,  ++,  + ]
R1576          [-, x,  +, o, nan, ±, Fx, F+,  +x, xx,  ++]
A1582    [-, x, ±, o,  +, nan, Fx, F+, α,  +x, x+, xx, ...
dtype: object

In [43]:
df[rt_cols] = df[rt_cols].apply(lambda col: col.str.strip()) # Clean text data: strip whitespace from all entries in selected columns
df[rt_cols].apply(pd.Series.unique) # Inspect unique values to verify consistency (e.g., no duplicates due to spacing)

W1521                            [-, +, ±, x, nan, F+, ++]
N1524                            [-, x, ±, +, nan, F±, ++]
A1526                             [-, x, o, +, nan, Fx, ±]
S1526                   [-, x, +, ±, nan, Fx, F+, xx, (±)]
R1527                [-, x, o, (+), nan, Fx, ±, F+, xx, +]
S1529              [-, x, +, ±, nan, F+, (+), xx, ±+, (±)]
A1530        [-, o, +, ±, x, nan, F+, Fx, (+), xx, ++, +x]
R1532            [-, o, x, ±, +, nan, F+, Fx, ++, +x, (±)]
R1541             [-, o, x, ±, +, nan, F+, Fx, xx, ±+, +x]
S1542                 [-, o, x, ±, +, nan, F+, Fx, xx, +x]
N1542             [-, x, o, ±, nan, +, F+, Fx, xx, ox, +x]
N1543                     [-, x, o, nan, +, Fx, xx, ox, ±]
S1544              [-, +, ±, x, nan, F+, Fx, xx, ++, +x, ]
W1545                 [-, x, o, +, nan, ±, F+, Fx, xx, +x]
A1548               [-, +, ±, x, nan, F+, Fx, +x, xx, (±)]
A1551             [-, x, ±, o, +, nan, F+, Fx, xx, +x, ++]
A1555                         [-, x, o, +, nan, ±, Fx, xx]
R1557             [-, x, o, +, nan, ±, F+, Fx, xx, +x, ++]
A1559            [-, x, ±, +, nan, Fx, F±, F+, +x, xx, ++]
A1566           [-, x, +, ±, nan, Fx, F+, +x, ++, xx, (o)]
R1567                     [-, x, o, nan, +, Fx, ±, xx, +x]
S1570             [-, x, +, ±, nan, o, Fx, F+, +x, xx, ++]
R1576             [-, x, +, o, nan, ±, Fx, F+, +x, xx, ++]
A1582    [-, x, ±, o, +, nan, Fx, F+, α, +x, x+, xx, ++...
dtype: object

In [44]:
df[rt_cols] = df[rt_cols].apply(lambda col: col.str.strip())
df[rt_cols]

,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,+,x,x,x,-,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x
2,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x
3,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±
4,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,-,-,x,x,x,+,-,+,x,x,x,x,-,x,-,x,x,x,x,x,x,+,x,+
406,x,-,-,+,-,+,+,-,+,+,x,x,+,+,-,-,x,+,+,-,x,+,x,+
407,x,-,x,x,x,-,-,-,+,+,x,-,-,+,-,x,x,x,+,+,x,x,+,-
408,±,-,+,+,-,+,+,+,+,+,-,-,+,±,+,+,+,+,+,+,-,+,+,+
409,x,x,-,-,-,-,x,-,x,x,-,-,x,-,x,x,-,x,x,x,x,-,+,x

## Extraction and frequency analysis of symbols

In [45]:
# Extract and combine unique values from all selected columns
# Each column's unique values are added to a single list (symbols)
symbols = []
for symbol_lst in df[rt_cols].apply(pd.Series.unique):
    symbols = symbols + list(symbol_lst)

In [46]:
symbols = []
for symbol_lst in df[rt_cols].apply(pd.Series.unique):
    symbols += list(symbol_lst)

symbols = list(set(symbols))

In [47]:
# For each unique symbol, count the number of rows in which it appears
# across any of the selected columns
symbol_counts = []
for symbol in set(symbols):
    mask = df.isin([symbol]).any(axis=1) # Create a boolean mask: True if the symbol appears in any column of the row
    #print( symbol, "\t", len(df[mask]))
    symbol_counts.append((symbol, len(df[mask]))) # Store the symbol and its corresponding row count

In [48]:
# Sort symbol-frequency pairs by count in ascending order
# This helps identify least and most frequent symbols
symbol_counts = sorted(symbol_counts, key=lambda t: t[1])
symbol_counts

[('', 1),
 ('±x', 1),
 ('±+', 1),
 ('α', 1),
 ('(o)', 1),
 ('x+', 1),
 ('F±', 1),
 ('ox', 2),
 ('(+)', 4),
 ('(±)', 5),
 ('o', 8),
 ('F+', 9),
 ('Fx', 14),
 ('++', 18),
 ('+x', 26),
 ('±', 34),
 ('xx', 34),
 ('+', 185),
 ('x', 265),
 ('-', 288),
 (nan, 410)]

## Replace and clean up symbols

In [49]:
rows, cols = np.where(df == ".")

for r, c in zip(rows, cols):
    print(f"Row: {r}, Column: {df.columns[c]}")

In [79]:
"""
Detect and report all occurrences of blank values (" ") in the dataset.

The script scans the DataFrame for cells containing a single space and
returns their positions as (row, column-name) pairs to help identify
data quality issues such as missing or improperly formatted entries.
"""

import numpy as np

rows, cols = np.where(df == " ")

for r, c in zip(rows, cols):
    print(f"Row: {r}, Column: {df.columns[c]}")

In [80]:
for r, c in zip(rows, cols):
    df.loc[df.index[r], df.columns[c]] = np.nan

In [81]:
df = df.replace(".", np.nan)

In [82]:
df = df.replace("-", np.nan)

In [83]:
mask = df.isin([repl]).any(axis=1)
df[rt_cols][mask]

NameError: name 'repl' is not defined

In [84]:
df.head()

,Name,"Stand (Kurfürsten, Fürsten, etc.)",Reichkreis,Reichs-\nmatrikel\n1521,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,Anmerkung,Unnamed: 33,count_+,count_x,count_o,count_±,count_Fx,count_F+,count_F±,count_++,count_xx,count_±+,count_(x),count_(o),count_(±),count_+x,count_ox,count_total
0,Böhmen,Kurfürsten,NaN,4,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Brandenburg,Kurfürsten,oS,7,23,7,16,4,+,x,x,x,NaN,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x,NaN,NaN,3,16,4,0,0,0,0,0,0,0,0,0,0,0,0,23
2,Köln,Kurfürsten,KR,3,24,9,15,0,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x,NaN,NaN,9,15,0,0,0,0,0,0,0,0,0,0,0,0,0,24
3,Mainz,Kurfürsten,KR,1,24,14,10,23,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±,NaN,NaN,0,1,9,14,0,0,0,0,0,0,0,0,0,0,0,24
4,Pfalz,Kurfürsten,KR,5,23,11,12,20,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o,NaN,NaN,2,2,11,9,0,0,0,0,0,0,0,0,0,0,0,24

In [56]:
for entry in df[2:20].itertuples():
    print(entry[1], entry[2], entry[5], entry[9:25])

Köln Kurfürsten 24 ('+', 'x', 'x', '+', 'x', '+', '+', 'x', 'x', 'x', 'x', 'x', '+', 'x', '+', 'x')
Mainz Kurfürsten 24 ('±', 'x', 'o', '±', 'o', '±', '±', '±', '±', '±', 'o', 'o', '±', 'o', '±', '±')
Pfalz Kurfürsten 23 ('±', '±', 'o', '±', 'o', '±', 'x', '+', 'x', '+', 'o', 'o', '±', 'o', '±', 'o')
Sachsen Kurfürsten 20 ('x', 'x', '+', nan, '(+)', 'x', nan, 'x', 'x', 'x', 'x', nan, '+', 'x', '+', 'x')
Trier Kurfürsten 24 ('+', '±', 'x', '+', 'x', '+', 'x', 'x', 'x', 'x', 'x', 'x', '+', 'x', '+', '+')
Augsburg Geistliche Fürsten 22 ('+', 'x', nan, 'x', 'x', '+', '+', '+', '+', 'x', nan, 'x', '+', '+', '+', '±')
Bamberg Geistliche Fürsten 24 ('±', '+', 'o', 'x', 'o', '±', '+', '+', '+', 'x', '±', 'x', 'x', 'x', 'x', 'x')
Basel Geistliche Fürsten 14 ('x', nan, nan, nan, nan, 'x', 'x', 'x', 'x', 'x', nan, nan, 'x', nan, nan, 'x')
Besançon (Eb) Geistliche Fürsten 4 (nan, nan, nan, nan, nan, 'x', nan, nan, 'x', nan, nan, nan, nan, nan, nan, nan)
Brandenburg Geistliche Fürsten 1 ('+', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan)
Bremen (Eb) Geistliche Fürsten 16 ('+', nan, nan, 'x', nan, 'x', '+', 'x', '+', 'x', 'x', nan, '+', 'x', '+', nan)
Brixen Geistliche Fürsten 18 (nan, '+', '+', 'x', nan, 'x', '+', 'x', nan, 'x', nan, 'x', nan, 'x', '+', '+')
Cambrai Geistliche Fürsten 8 (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'x', 'x', 'x', '+')
Camyn (Kammin) Geistliche Fürsten 4 (nan, nan, nan, nan, 'x', nan, 'x', nan, nan, 'x', nan, nan, nan, nan, 'x', nan)
Chiemsee Geistliche Fürsten 3 (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'x', 'x', nan, 'x', nan, nan)
Chur Geistliche Fürsten 6 (nan, nan, nan, nan, nan, '+', '+', 'x', 'x', nan, nan, nan, nan, 'x', 'x', nan)
Eichstädt Geistliche Fürsten 22 ('x', 'x', nan, 'x', nan, 'x', '+', 'x', '+', 'x', '+', 'x', 'x', 'x', '+', '+')
Freising Geistliche Fürsten 22 (nan, 'x', 'x', 'x', nan, 'x', 'x', 'x', 'x', '+', 'x', 'x', '+', 'x', '+', 'x')

In [57]:
import numpy as np

# Clean whitespace
df = df.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

# Remove "-"
df = df.replace("-", np.nan)

df[rt_cols]

,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,+,x,x,x,NaN,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x
2,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x
3,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±
4,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,NaN,NaN,x,x,x,+,NaN,+,x,x,x,x,NaN,x,NaN,x,x,x,x,x,x,+,x,+
406,x,NaN,NaN,+,NaN,+,+,NaN,+,+,x,x,+,+,NaN,NaN,x,+,+,NaN,x,+,x,+
407,x,NaN,x,x,x,NaN,NaN,NaN,+,+,x,NaN,NaN,+,NaN,x,x,x,+,+,x,x,+,NaN
408,±,NaN,+,+,NaN,+,+,+,+,+,NaN,NaN,+,±,+,+,+,+,+,+,NaN,+,+,+
409,x,x,NaN,NaN,NaN,NaN,x,NaN,x,x,NaN,NaN,x,NaN,x,x,NaN,x,x,x,x,NaN,+,x

## Counting frequency of symbols

In [58]:
symbols = ["+", "x", "o", "±", "Fx", "F+", "F±", "++", "xx", "±+", "(x)","(o)", "(±)", "+x", "ox"]

for s in symbols:
    df[f"count_{s}"] = (df == s).sum(axis=1)

df["count_total"] = df[[f"count_{s}" for s in symbols]].sum(axis=1)
df

,Name,"Stand (Kurfürsten, Fürsten, etc.)",Reichkreis,Reichs-\nmatrikel\n1521,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,Anmerkung,Unnamed: 33,count_+,count_x,count_o,count_±,count_Fx,count_F+,count_F±,count_++,count_xx,count_±+,count_(x),count_(o),count_(±),count_+x,count_ox,count_total
0,Böhmen,Kurfürsten,NaN,4,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Brandenburg,Kurfürsten,oS,7,23,7,16,4,+,x,x,x,NaN,x,o,o,o,o,x,x,+,x,+,x,x,x,x,x,x,x,x,x,NaN,NaN,3,16,4,0,0,0,0,0,0,0,0,0,0,0,0,23
2,Köln,Kurfürsten,KR,3,24,9,15,0,+,x,x,+,x,+,+,x,x,x,x,x,+,x,+,x,x,x,x,+,x,+,+,x,NaN,NaN,9,15,0,0,0,0,0,0,0,0,0,0,0,0,0,24
3,Mainz,Kurfürsten,KR,1,24,14,10,23,±,x,o,±,o,±,±,±,±,±,o,o,±,o,±,±,o,o,±,±,o,±,o,±,NaN,NaN,0,1,9,14,0,0,0,0,0,0,0,0,0,0,0,24
4,Pfalz,Kurfürsten,KR,5,23,11,12,20,±,±,o,±,o,±,x,+,x,+,o,o,±,o,±,o,o,o,±,±,o,±,o,o,NaN,NaN,2,2,11,9,0,0,0,0,0,0,0,0,0,0,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,Wetzlar,Reichsstädte,R,51,19,4,15,0,NaN,NaN,x,x,x,+,NaN,+,x,x,x,x,NaN,x,NaN,x,x,x,x,x,x,+,x,+,NaN,NaN,4,15,0,0,0,0,0,0,0,0,0,0,0,0,0,19
406,Wimpfen,Reichsstädte,S,8,18,11,6,0,x,NaN,NaN,+,NaN,+,+,NaN,+,+,x,x,+,+,NaN,NaN,x,+,+,NaN,x,+,x,+,NaN,NaN,11,6,0,0,0,0,0,0,0,0,0,0,0,0,0,17
407,Windsheim,Reichsstädte,F,6,16,6,10,0,x,NaN,x,x,x,NaN,NaN,NaN,+,+,x,NaN,NaN,+,NaN,x,x,x,+,+,x,x,+,NaN,NaN,NaN,6,10,0,0,0,0,0,0,0,0,0,0,0,0,0,16
408,Worms,Reichsstädte,R,47,19,19,0,2,±,NaN,+,+,NaN,+,+,+,+,+,NaN,NaN,+,±,+,+,+,+,+,+,NaN,+,+,+,NaN,NaN,17,0,0,2,0,0,0,0,0,0,0,0,0,0,0,19
409,Zell/Hammersbach,Reichsstädte,S,60,14,1,13,0,x,x,NaN,NaN,NaN,NaN,x,NaN,x,x,NaN,NaN,x,NaN,x,x,NaN,x,x,x,x,NaN,+,x,NaN,NaN,1,13,0,0,0,0,0,0,0,0,0,0,0,0,0,14

In [85]:
df[["Besuchte\nRTT", "Persönl.\nbesuchte\nRTT", "Vertretene\nRTT", "Abschieds-\nunterzeichnung"]]
df_attendance = df[["Besuchte\nRTT", "Persönl.\nbesuchte\nRTT", "Vertretene\nRTT", "Abschieds-\nunterzeichnung"]]
df_attendance

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung
0,NaN,NaN,NaN,0
1,23,7,16,4
2,24,9,15,0
3,24,14,10,23
4,23,11,12,20
...,...,...,...,...
405,19,4,15,0
406,18,11,6,0
407,16,6,10,0
408,19,19,0,2
409,14,1,13,0

In [74]:
df_attendance_counts = df_attendance.copy()

df_attendance_counts["count_total"] = df["count_total"]
df_attendance_counts["count_+"] = df["count_+"]
df_attendance_counts["count_x"] = df["count_x"]
df_attendance_counts["count_o"] = df["count_o"]
df_attendance_counts["count_±"] = df["count_±"]
df_attendance_counts["count_Fx"] = df["count_Fx"]
df_attendance_counts["count_F+"] = df["count_F+"]
df_attendance_counts["count_F±"] = df["count_F±"]
df_attendance_counts["count_++"] = df["count_++"]
df_attendance_counts["count_xx"] = df["count_xx"]
df_attendance_counts["count_±+"] = df["count_±+"]
df_attendance_counts["count_(x)"] = df["count_(x)"]
df_attendance_counts["count_(o)"] = df["count_(o)"]
df_attendance_counts["count_(±)"] = df["count_(±)"]
df_attendance_counts["count_+x"] = df["count_+x"]
df_attendance_counts["count_ox"] = df["count_ox"]

df_attendance_counts

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,count_total,count_+,count_x,count_o,count_±,count_Fx,count_F+,count_F±,count_++,count_xx,count_±+,count_(x),count_(o),count_(±),count_+x,count_ox
0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,23,7,16,4,23,3,16,4,0,0,0,0,0,0,0,0,0,0,0,0
2,24,9,15,0,24,9,15,0,0,0,0,0,0,0,0,0,0,0,0,0
3,24,14,10,23,24,0,1,9,14,0,0,0,0,0,0,0,0,0,0,0
4,23,11,12,20,24,2,2,11,9,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,19,4,15,0,19,4,15,0,0,0,0,0,0,0,0,0,0,0,0,0
406,18,11,6,0,17,11,6,0,0,0,0,0,0,0,0,0,0,0,0,0
407,16,6,10,0,16,6,10,0,0,0,0,0,0,0,0,0,0,0,0,0
408,19,19,0,2,19,17,0,0,2,0,0,0,0,0,0,0,0,0,0,0
409,14,1,13,0,14,1,13,0,0,0,0,0,0,0,0,0,0,0,0,0

## Mapping

In [86]:
"""
Dictionary mapping symbolic input patterns to corresponding encoded sequences.

Each key represents a specific symbol or combination of symbols, while the 
associated value is a list of one or more codes that encode or transform 
that input into a normalized or structured representation.
"""
mapping = {
    "x": ["a"],
    "+": ["b"],  
    "o": ["c"],
    "±": ["d"],

    "Fx": ["y", "a"],
    "F+": ["y", "b"],
    "F±": ["y", "d"],

    "++": ["b", "x"],
    "xx": ["a", "x"],
    "±+": ["d", "b"],

    "(x)": ["a", "z"],
    "(o)": ["c", "z"],
    "(±)": ["d", "z"],

    "+x": ["b", "a"],
    "ox": ["c", "a"]
}

In [87]:
"""
This code takes a subset of columns (`rt_cols`) from the DataFrame `df`
and replaces each string value according to the predefined `mapping` dictionary.

Process:
- For each column in `rt_cols`, apply a transformation element-wise.
- For each cell value `x`:
    - If `x` is a string, look it up in `mapping`.
        - If a match is found, the corresponding list of codes is joined
          into a single comma-separated string (e.g., ["a", "b"] → "a,b").
        - If no match is found, an empty list is returned by default,
          resulting in an empty string.
    - If `x` is not a string (e.g., NaN or numeric), it is left unchanged.
Result:
- Returns a new DataFrame (`df_mapped`) with the same structure as the
  selected columns, but with symbolic values converted into their encoded
  string representations.
"""

df_mapped = df[rt_cols].apply(
    lambda col: col.map(
        lambda x: ",".join(mapping.get(x, [])) if isinstance(x, str) else x
    )
)

In [88]:
"""
Map a single value `x` to its encoded representation using `mapping`.

- If `x` exists as a key in the `mapping` dictionary:
    - Retrieve the corresponding list of codes (e.g., ["a", "b"])
    - Join them into a comma-separated string (e.g., "a,b")
- If `x` is not found in `mapping`:
    - Return `x` unchanged
"""

lambda x: ",".join(mapping[x]) if x in mapping else x

In [64]:
df_mapped

,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,b,a,a,a,NaN,a,c,c,c,c,a,a,b,a,b,a,a,a,a,a,a,a,a,a
2,b,a,a,b,a,b,b,a,a,a,a,a,b,a,b,a,a,a,a,b,a,b,b,a
3,d,a,c,d,c,d,d,d,d,d,c,c,d,c,d,d,c,c,d,d,c,d,c,d
4,d,d,c,d,c,d,a,b,a,b,c,c,d,c,d,c,c,c,d,d,c,d,c,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,NaN,NaN,a,a,a,b,NaN,b,a,a,a,a,NaN,a,NaN,a,a,a,a,a,a,b,a,b
406,a,NaN,NaN,b,NaN,b,b,NaN,b,b,a,a,b,b,NaN,NaN,a,b,b,NaN,a,b,a,b
407,a,NaN,a,a,a,NaN,NaN,NaN,b,b,a,NaN,NaN,b,NaN,a,a,a,b,b,a,a,b,NaN
408,d,NaN,b,b,NaN,b,b,b,b,b,NaN,NaN,b,d,b,b,b,b,b,b,NaN,b,b,b
409,a,a,NaN,NaN,NaN,NaN,a,NaN,a,a,NaN,NaN,a,NaN,a,a,NaN,a,a,a,a,NaN,b,a

In [65]:
df_mapped[300:330]

,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,a,a,NaN,a,a,a,b,a,a,a,a,a
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a
302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,a,"b,a",a,NaN,a,b,a,"a,x","b,a","b,a",a,a,"a,x",a,"b,a"
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,NaN,b,"b,a",b,a,a,b,b
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,b,"b,x",NaN,b,NaN,NaN,NaN,NaN,a,a,a,NaN,b,a,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,a,a,a,a,a,a,a,a,a,NaN,a,a,a
312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b,NaN,a,b,a,NaN,a,NaN,NaN,NaN,b,NaN,NaN,NaN,NaN
313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,a,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b,b
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,NaN,b,a,a
316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,a,a,a,a,NaN,b,NaN,a,a,a,a,a,a,c,b
319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"b,a",a,a,a,NaN,NaN,"a,x",a,a,d,"b,a",d,b,a,"b,a"
320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,a,b,NaN,b,NaN,a,NaN,NaN,NaN,a,a
321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,b,NaN,b,NaN,NaN,b,b,NaN,b,b,NaN,NaN,b,NaN,b,b,b,b,b,b,a,b,b,NaN
325,a,a,NaN,a,a,b,b,a,a,NaN,NaN,a,a,a,NaN,b,a,a,a,a,a,a,a,a
326,b,b,d,NaN,NaN,b,,NaN,b,b,b,b,b,b,"d,z",d,d,b,d,d,b,b,b,d
327,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,a,NaN,NaN,NaN,a,b,b,a,a,b,NaN,a,a,b,NaN,b,a,a,a,a,a,a,a,b

In [89]:
df_combined = df_attendance.join(df_mapped)

In [90]:
df_combined

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23,7,16,4,b,a,a,a,NaN,a,c,c,c,c,a,a,b,a,b,a,a,a,a,a,a,a,a,a
2,24,9,15,0,b,a,a,b,a,b,b,a,a,a,a,a,b,a,b,a,a,a,a,b,a,b,b,a
3,24,14,10,23,d,a,c,d,c,d,d,d,d,d,c,c,d,c,d,d,c,c,d,d,c,d,c,d
4,23,11,12,20,d,d,c,d,c,d,a,b,a,b,c,c,d,c,d,c,c,c,d,d,c,d,c,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,19,4,15,0,NaN,NaN,a,a,a,b,NaN,b,a,a,a,a,NaN,a,NaN,a,a,a,a,a,a,b,a,b
406,18,11,6,0,a,NaN,NaN,b,NaN,b,b,NaN,b,b,a,a,b,b,NaN,NaN,a,b,b,NaN,a,b,a,b
407,16,6,10,0,a,NaN,a,a,a,NaN,NaN,NaN,b,b,a,NaN,NaN,b,NaN,a,a,a,b,b,a,a,b,NaN
408,19,19,0,2,d,NaN,b,b,NaN,b,b,b,b,b,NaN,NaN,b,d,b,b,b,b,b,b,NaN,b,b,b
409,14,1,13,0,a,a,NaN,NaN,NaN,NaN,a,NaN,a,a,NaN,NaN,a,NaN,a,a,NaN,a,a,a,a,NaN,b,a

In [115]:
cols_att = [
    "Besuchte\nRTT",
    "Persönl.\nbesuchte\nRTT",
    "Vertretene\nRTT",
    "Abschieds-\nunterzeichnung"
]

cols_map = [
    "W1521","N1524","A1526","S1526","R1527","S1529","A1530",
    "R1532","R1541","S1542","N1542","N1543","S1544","W1545",
    "A1548","A1551","A1555","R1557","A1559","A1566","R1567",
    "S1570","R1576","A1582"
]

df_combined = df_combined[cols_att + cols_map]

In [116]:
df_combined

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582
0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23.0,7,16,4,b,a,a,a,NaN,a,c,c,c,c,a,a,b,a,b,a,a,a,a,a,a,a,a,a
2,24.0,9,15,0,b,a,a,b,a,b,b,a,a,a,a,a,b,a,b,a,a,a,a,b,a,b,b,a
3,24.0,14,10,23,d,a,c,d,c,d,d,d,d,d,c,c,d,c,d,d,c,c,d,d,c,d,c,d
4,23.0,11,12,20,d,d,c,d,c,d,a,b,a,b,c,c,d,c,d,c,c,c,d,d,c,d,c,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,19.0,4,15,0,NaN,NaN,a,a,a,b,NaN,b,a,a,a,a,NaN,a,NaN,a,a,a,a,a,a,b,a,b
406,18.0,11,6,0,a,NaN,NaN,b,NaN,b,b,NaN,b,b,a,a,b,b,NaN,NaN,a,b,b,NaN,a,b,a,b
407,16.0,6,10,0,a,NaN,a,a,a,NaN,NaN,NaN,b,b,a,NaN,NaN,b,NaN,a,a,a,b,b,a,a,b,NaN
408,19.0,19,0,2,d,NaN,b,b,NaN,b,b,b,b,b,NaN,NaN,b,d,b,b,b,b,b,b,NaN,b,b,b
409,14.0,1,13,0,a,a,NaN,NaN,NaN,NaN,a,NaN,a,a,NaN,NaN,a,NaN,a,a,NaN,a,a,a,a,NaN,b,a

## Count symbols and check number of symbols with number of attendance

## 1) Count personal attendance (persönliche Anwesenheit + Abschied unterzeichnet)

## 2) Count represented by envoy (von Gesandten vertreten)

In [121]:
df_envoy = df_combined

mapping_cols = [
    "W1521","N1524","A1526","S1526","R1527","S1529","A1530",
    "R1527","R1541","S1542","N1542","N1543","S1544","W1545",
    "A1548","A1551","A1555","R1557","A1559","A1566","R1567",
    "S1570","R1576","A1582"
]

df_envoy["mapping_total"] = df[mapping_cols].astype(str).apply(
    lambda row: row.str.contains("a", na=False).sum(),
    axis=1
)

df_envoy["match_a"] = df_envoy["a_total"] == df_envoy["Vertretene\nRTT"]
df_envoy[["Vertretene\nRTT", "a_total", "match_a"] + mapping_cols]
df_envoy[df_envoy["match_a"] == False]

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,mapping_total,match,a_total,match_a
0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,0,False
1,23.0,7,16,4,b,a,a,a,NaN,a,c,c,c,c,a,a,b,a,b,a,a,a,a,a,a,a,a,a,0,True,0,False
2,24.0,9,15,0,b,a,a,b,a,b,b,a,a,a,a,a,b,a,b,a,a,a,a,b,a,b,b,a,0,True,0,False
3,24.0,14,10,23,d,a,c,d,c,d,d,d,d,d,c,c,d,c,d,d,c,c,d,d,c,d,c,d,0,True,0,False
4,23.0,11,12,20,d,d,c,d,c,d,a,b,a,b,c,c,d,c,d,c,c,c,d,d,c,d,c,c,0,False,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,19.0,4,15,0,NaN,NaN,a,a,a,b,NaN,b,a,a,a,a,NaN,a,NaN,a,a,a,a,a,a,b,a,b,0,True,0,False
406,18.0,11,6,0,a,NaN,NaN,b,NaN,b,b,NaN,b,b,a,a,b,b,NaN,NaN,a,b,b,NaN,a,b,a,b,0,False,0,False
407,16.0,6,10,0,a,NaN,a,a,a,NaN,NaN,NaN,b,b,a,NaN,NaN,b,NaN,a,a,a,b,b,a,a,b,NaN,0,True,0,False
408,19.0,19,0,2,d,NaN,b,b,NaN,b,b,b,b,b,NaN,NaN,b,d,b,b,b,b,b,b,NaN,b,b,b,0,True,0,False
409,14.0,1,13,0,a,a,NaN,NaN,NaN,NaN,a,NaN,a,a,NaN,NaN,a,NaN,a,a,NaN,a,a,a,a,NaN,b,a,0,True,0,False

## 3) Count general attendance (personal attendance + represented by envoy)

In [118]:
df_total = df_combined

mapping_cols = [
    "W1521","N1524","A1526","S1526","R1527","S1529","A1530",
    "R1532","R1541","S1542","N1542","N1543","S1544","W1545",
    "A1548","A1551","A1555","R1557","A1559","A1566","R1567",
    "S1570","R1576","A1582"
]

df_total["mapping_total"] = df_total[mapping_cols].notna().sum(axis=1)

df_total["match"] = df_total["mapping_total"] == df_total["Besuchte\nRTT"]
df_total[(df_total.match == False)]

,Besuchte\nRTT,Persönl.\nbesuchte\nRTT,Vertretene\nRTT,Abschieds-\nunterzeichnung,W1521,N1524,A1526,S1526,R1527,S1529,A1530,R1532,R1541,S1542,N1542,N1543,S1544,W1545,A1548,A1551,A1555,R1557,A1559,A1566,R1567,S1570,R1576,A1582,mapping_total,match
0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
4,23.0,11,12,20,d,d,c,d,c,d,a,b,a,b,c,c,d,c,d,c,c,c,d,d,c,d,c,c,24,False
5,20.0,6,14,0+,a,a,b,NaN,,a,NaN,a,a,a,a,NaN,b,a,b,a,a,a,a,b,a,a,a,b,21,False
26,2.0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,False
59,22.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
60,19.0,1,18,0,NaN,NaN,a,NaN,NaN,a,a,a,a,a,a,a,a,a,a,a,a,"y,b","y,a","y,a","y,a","y,a","y,a","y,a",20,False
79,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,a,a,a,a,NaN,NaN,a,NaN,NaN,a,NaN,NaN,7,False
150,19.0,3,16,0,b,NaN,NaN,a,NaN,,,b,"a,x","a,x","a,x","a,x","a,x",a,a,a,a,"a,x","a,x",b,"a,x","a,x",a,a,21,False
154,23.0,14,9,15,b,NaN,NaN,"a,x","a,x","d,b","b,x","b,x","d,b","a,x",c,"c,a",a,a,a,d,d,d,d,d,d,c,d,d,22,False
156,19.0,7,12,0,b,b,NaN,NaN,NaN,,,a,"b,a",a,"a,x",a,"b,x","a,x",b,"a,x",a,a,"b,a","b,a",a,"a,x",a,a,21,False
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"a,x","a,x",a,3,False
160,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
162,15.0,10,11,0,b,a,a,b,NaN,d,d,NaN,b,NaN,NaN,NaN,b,a,NaN,NaN,a,a,a,a,a,b,a,a,17,False
163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,b,a,a,4,False
164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,a,a,4,False
177,22.0,8,14,0,b,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,b,a,b,a,a,b,b,"b,x","a,x",a,b,b,15,False
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
218,3.0,2,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,False
225,16.0,2,14,1,NaN,b,NaN,NaN,NaN,"d,z",NaN,b,NaN,a,a,a,NaN,a,a,a,a,a,a,a,a,a,a,a,17,False
253,15.0,0,15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,"a,x",a,a,"a,x",a,a,a,a,a,a,"c,z",NaN,a,a,a,16,False
264,15.0,13,2,1,NaN,NaN,NaN,NaN,NaN,NaN,"b,x",b,d,NaN,NaN,a,"b,a",a,b,"b,x",b,"b,x","b,x","b,x",b,d,"b,x","b,a",16,False
291,20.0,6,14,3,b,b,NaN,d,NaN,"d,z","b,a",a,"a,x","a,x","a,x",a,"a,x",a,"b,a",a,"a,x",a,"a,x","a,x",NaN,"a,x","a,x",,21,False
296,3.0,0,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
298,16.0,0,16,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,17,False
307,8.0,5,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a,a,NaN,b,"b,a",b,a,a,b,b,9,False
325,21.0,3,18,0,a,a,NaN,a,a,b,b,a,a,NaN,NaN,a,a,a,NaN,b,a,a,a,a,a,a,a,a,20,False
326,19.0,19,0,7,b,b,d,NaN,NaN,b,,NaN,b,b,b,b,b,b,"d,z",d,d,b,d,d,b,b,b,d,21,False
335,20.0,(8),(12),0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
357,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
361,20.0,20,0,0,b,b,b,b,b,b,b,b,b,b,b,NaN,b,b,b,b,NaN,b,b,b,NaN,b,b,b,21,False
363,20.0,29,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
369,6.0,6,0,0,b,NaN,NaN,b,NaN,NaN,b,NaN,NaN,NaN,NaN,NaN,b,NaN,NaN,b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,False
370,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
372,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
377,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
381,22.0,22,0,7,b,b,NaN,b,d,d,b,"d,z",d,b,b,b,b,b,b,b,b,d,b,b,d,b,d,b,23,False
383,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
387,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
392,16.0,16,0,5,b,NaN,NaN,"d,z",b,"d,z",b,b,b,d,NaN,NaN,d,NaN,b,b,b,b,b,b,NaN,d,b,b,18,False
395,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
401,20.0,19,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False
406,18.0,11,6,0,a,NaN,NaN,b,NaN,b,b,NaN,b,b,a,a,b,b,NaN,NaN,a,b,b,NaN,a,b,a,b,17,False